# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.edits_summary import EditsSummary  # noqa: E501
from swagger_client.rest import ApiException


class TestEditsSummary(unittest.TestCase):
    """EditsSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditsSummary(self):
        """Test EditsSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.edits_summary.EditsSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
