# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_endpoints_api import CustomSpeechEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechEndpointsApi(unittest.TestCase):
    """CustomSpeechEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_endpoints_api.CustomSpeechEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_endpoints_create(self):
        """Test case for endpoints_create

        Creates a new endpoint.  # noqa: E501
        """
        pass

    def test_endpoints_delete(self):
        """Test case for endpoints_delete

        Deletes the endpoint identified by the given ID.  # noqa: E501
        """
        pass

    def test_endpoints_get(self):
        """Test case for endpoints_get

        Gets the endpoint identified by the given ID.  # noqa: E501
        """
        pass

    def test_endpoints_list(self):
        """Test case for endpoints_list

        Gets the list of endpoints for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_endpoints_list_supported_locales(self):
        """Test case for endpoints_list_supported_locales

        Gets a list of supported locales for endpoint creations.  # noqa: E501
        """
        pass

    def test_endpoints_update(self):
        """Test case for endpoints_update

        Updates the metadata of the endpoint identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
