# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.channel_combined_phrases import ChannelCombinedPhrases  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelCombinedPhrases(unittest.TestCase):
    """ChannelCombinedPhrases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelCombinedPhrases(self):
        """Test ChannelCombinedPhrases"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.channel_combined_phrases.ChannelCombinedPhrases()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
