# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_copy_authorization_definition import ModelCopyAuthorizationDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestModelCopyAuthorizationDefinition(unittest.TestCase):
    """ModelCopyAuthorizationDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelCopyAuthorizationDefinition(self):
        """Test ModelCopyAuthorizationDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_copy_authorization_definition.ModelCopyAuthorizationDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
