# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transcribe_api import TranscribeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTranscribeApi(unittest.TestCase):
    """TranscribeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transcribe_api.TranscribeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transcriptions_transcribe(self):
        """Test case for transcriptions_transcribe

        Synchronous transcription of an audio file.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
