# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transcribe_diarization_properties import TranscribeDiarizationProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestTranscribeDiarizationProperties(unittest.TestCase):
    """TranscribeDiarizationProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscribeDiarizationProperties(self):
        """Test TranscribeDiarizationProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transcribe_diarization_properties.TranscribeDiarizationProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
