# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TranscribeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def transcriptions_transcribe(self, api_version, audio, **kwargs):  # noqa: E501
        """Synchronous transcription of an audio file.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.transcriptions_transcribe(api_version, audio, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api_version: The requested api version. (required)
        :param file audio: The content of the audio file to be transcribed. The audio file must be shorter than 2 hours in audio duration and smaller than 250 MB in size. (required)
        :param str definition: Metadata for a transcription request. This field contains a JSON-serialized object of type `TranscribeDefinition`.
        :return: TranscribeResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.transcriptions_transcribe_with_http_info(api_version, audio, **kwargs)  # noqa: E501
        else:
            (data) = self.transcriptions_transcribe_with_http_info(api_version, audio, **kwargs)  # noqa: E501
            return data

    def transcriptions_transcribe_with_http_info(self, api_version, audio, **kwargs):  # noqa: E501
        """Synchronous transcription of an audio file.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.transcriptions_transcribe_with_http_info(api_version, audio, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str api_version: The requested api version. (required)
        :param file audio: The content of the audio file to be transcribed. The audio file must be shorter than 2 hours in audio duration and smaller than 250 MB in size. (required)
        :param str definition: Metadata for a transcription request. This field contains a JSON-serialized object of type `TranscribeDefinition`.
        :return: TranscribeResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['api_version', 'audio', 'definition']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method transcriptions_transcribe" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'api_version' is set
        if self.api_client.client_side_validation and ('api_version' not in params or
                                                       params['api_version'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `api_version` when calling `transcriptions_transcribe`")  # noqa: E501
        # verify the required parameter 'audio' is set
        if self.api_client.client_side_validation and ('audio' not in params or
                                                       params['audio'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `audio` when calling `transcriptions_transcribe`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'api_version' in params:
            query_params.append(('api-version', params['api_version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'audio' in params:
            local_var_files['audio'] = params['audio']  # noqa: E501
        if 'definition' in params:
            form_params.append(('definition', params['definition']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/transcriptions:transcribe', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TranscribeResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
