# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EndpointProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'logging_enabled': 'bool',
        'error': 'EntityError'
    }

    attribute_map = {
        'logging_enabled': 'loggingEnabled',
        'error': 'error'
    }

    def __init__(self, logging_enabled=None, error=None, _configuration=None):  # noqa: E501
        """EndpointProperties - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._logging_enabled = None
        self._error = None
        self.discriminator = None

        if logging_enabled is not None:
            self.logging_enabled = logging_enabled
        if error is not None:
            self.error = error

    @property
    def logging_enabled(self):
        """Gets the logging_enabled of this EndpointProperties.  # noqa: E501

        A value indicating whether content logging (audio & transcriptions) is being used for a deployment.  # noqa: E501

        :return: The logging_enabled of this EndpointProperties.  # noqa: E501
        :rtype: bool
        """
        return self._logging_enabled

    @logging_enabled.setter
    def logging_enabled(self, logging_enabled):
        """Sets the logging_enabled of this EndpointProperties.

        A value indicating whether content logging (audio & transcriptions) is being used for a deployment.  # noqa: E501

        :param logging_enabled: The logging_enabled of this EndpointProperties.  # noqa: E501
        :type: bool
        """

        self._logging_enabled = logging_enabled

    @property
    def error(self):
        """Gets the error of this EndpointProperties.  # noqa: E501


        :return: The error of this EndpointProperties.  # noqa: E501
        :rtype: EntityError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this EndpointProperties.


        :param error: The error of this EndpointProperties.  # noqa: E501
        :type: EntityError
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EndpointProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EndpointProperties):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EndpointProperties):
            return True

        return self.to_dict() != other.to_dict()
