# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Phrase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'int',
        'speaker': 'int',
        'offset_milliseconds': 'int',
        'duration_milliseconds': 'int',
        'text': 'str',
        'words': 'list[Word]',
        'locale': 'str',
        'confidence': 'float'
    }

    attribute_map = {
        'channel': 'channel',
        'speaker': 'speaker',
        'offset_milliseconds': 'offsetMilliseconds',
        'duration_milliseconds': 'durationMilliseconds',
        'text': 'text',
        'words': 'words',
        'locale': 'locale',
        'confidence': 'confidence'
    }

    def __init__(self, channel=None, speaker=None, offset_milliseconds=None, duration_milliseconds=None, text=None, words=None, locale=None, confidence=None, _configuration=None):  # noqa: E501
        """Phrase - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._channel = None
        self._speaker = None
        self._offset_milliseconds = None
        self._duration_milliseconds = None
        self._text = None
        self._words = None
        self._locale = None
        self._confidence = None
        self.discriminator = None

        if channel is not None:
            self.channel = channel
        if speaker is not None:
            self.speaker = speaker
        self.offset_milliseconds = offset_milliseconds
        self.duration_milliseconds = duration_milliseconds
        self.text = text
        if words is not None:
            self.words = words
        if locale is not None:
            self.locale = locale
        self.confidence = confidence

    @property
    def channel(self):
        """Gets the channel of this Phrase.  # noqa: E501

        The 0-based channel index. Only present if channel separation is enabled.  # noqa: E501

        :return: The channel of this Phrase.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this Phrase.

        The 0-based channel index. Only present if channel separation is enabled.  # noqa: E501

        :param channel: The channel of this Phrase.  # noqa: E501
        :type: int
        """

        self._channel = channel

    @property
    def speaker(self):
        """Gets the speaker of this Phrase.  # noqa: E501

        A unique integer number that is assigned to each speaker detected in the audio without particular order. Only present if speaker diarization is enabled.  # noqa: E501

        :return: The speaker of this Phrase.  # noqa: E501
        :rtype: int
        """
        return self._speaker

    @speaker.setter
    def speaker(self, speaker):
        """Sets the speaker of this Phrase.

        A unique integer number that is assigned to each speaker detected in the audio without particular order. Only present if speaker diarization is enabled.  # noqa: E501

        :param speaker: The speaker of this Phrase.  # noqa: E501
        :type: int
        """

        self._speaker = speaker

    @property
    def offset_milliseconds(self):
        """Gets the offset_milliseconds of this Phrase.  # noqa: E501

        The start offset of the phrase in milliseconds.  # noqa: E501

        :return: The offset_milliseconds of this Phrase.  # noqa: E501
        :rtype: int
        """
        return self._offset_milliseconds

    @offset_milliseconds.setter
    def offset_milliseconds(self, offset_milliseconds):
        """Sets the offset_milliseconds of this Phrase.

        The start offset of the phrase in milliseconds.  # noqa: E501

        :param offset_milliseconds: The offset_milliseconds of this Phrase.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and offset_milliseconds is None:
            raise ValueError("Invalid value for `offset_milliseconds`, must not be `None`")  # noqa: E501

        self._offset_milliseconds = offset_milliseconds

    @property
    def duration_milliseconds(self):
        """Gets the duration_milliseconds of this Phrase.  # noqa: E501

        The duration of the phrase in milliseconds.  # noqa: E501

        :return: The duration_milliseconds of this Phrase.  # noqa: E501
        :rtype: int
        """
        return self._duration_milliseconds

    @duration_milliseconds.setter
    def duration_milliseconds(self, duration_milliseconds):
        """Sets the duration_milliseconds of this Phrase.

        The duration of the phrase in milliseconds.  # noqa: E501

        :param duration_milliseconds: The duration_milliseconds of this Phrase.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and duration_milliseconds is None:
            raise ValueError("Invalid value for `duration_milliseconds`, must not be `None`")  # noqa: E501

        self._duration_milliseconds = duration_milliseconds

    @property
    def text(self):
        """Gets the text of this Phrase.  # noqa: E501

        The transcribed text of the phrase.  # noqa: E501

        :return: The text of this Phrase.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Phrase.

        The transcribed text of the phrase.  # noqa: E501

        :param text: The text of this Phrase.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def words(self):
        """Gets the words of this Phrase.  # noqa: E501

        The words that make up the phrase. Only present if word-level timestamps are enabled.  # noqa: E501

        :return: The words of this Phrase.  # noqa: E501
        :rtype: list[Word]
        """
        return self._words

    @words.setter
    def words(self, words):
        """Sets the words of this Phrase.

        The words that make up the phrase. Only present if word-level timestamps are enabled.  # noqa: E501

        :param words: The words of this Phrase.  # noqa: E501
        :type: list[Word]
        """

        self._words = words

    @property
    def locale(self):
        """Gets the locale of this Phrase.  # noqa: E501

        The locale of the phrase.  # noqa: E501

        :return: The locale of this Phrase.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Phrase.

        The locale of the phrase.  # noqa: E501

        :param locale: The locale of this Phrase.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def confidence(self):
        """Gets the confidence of this Phrase.  # noqa: E501

        The confidence value for the phrase.  # noqa: E501

        :return: The confidence of this Phrase.  # noqa: E501
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this Phrase.

        The confidence value for the phrase.  # noqa: E501

        :param confidence: The confidence of this Phrase.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and confidence is None:
            raise ValueError("Invalid value for `confidence`, must not be `None`")  # noqa: E501

        self._confidence = confidence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Phrase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Phrase):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Phrase):
            return True

        return self.to_dict() != other.to_dict()
