# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TranscribeDiarizationProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'max_speakers': 'int'
    }

    attribute_map = {
        'enabled': 'enabled',
        'max_speakers': 'maxSpeakers'
    }

    def __init__(self, enabled=None, max_speakers=None, _configuration=None):  # noqa: E501
        """TranscribeDiarizationProperties - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._enabled = None
        self._max_speakers = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if max_speakers is not None:
            self.max_speakers = max_speakers

    @property
    def enabled(self):
        """Gets the enabled of this TranscribeDiarizationProperties.  # noqa: E501

        Gets or sets a value indicating whether speaker diarization is enabled.  # noqa: E501

        :return: The enabled of this TranscribeDiarizationProperties.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this TranscribeDiarizationProperties.

        Gets or sets a value indicating whether speaker diarization is enabled.  # noqa: E501

        :param enabled: The enabled of this TranscribeDiarizationProperties.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def max_speakers(self):
        """Gets the max_speakers of this TranscribeDiarizationProperties.  # noqa: E501

        Gets or sets a hint for the maximum number of speakers for diarization. Must be greater than 1 and less than 36.  # noqa: E501

        :return: The max_speakers of this TranscribeDiarizationProperties.  # noqa: E501
        :rtype: int
        """
        return self._max_speakers

    @max_speakers.setter
    def max_speakers(self, max_speakers):
        """Sets the max_speakers of this TranscribeDiarizationProperties.

        Gets or sets a hint for the maximum number of speakers for diarization. Must be greater than 1 and less than 36.  # noqa: E501

        :param max_speakers: The max_speakers of this TranscribeDiarizationProperties.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                max_speakers is not None and max_speakers > 35):  # noqa: E501
            raise ValueError("Invalid value for `max_speakers`, must be a value less than or equal to `35`")  # noqa: E501
        if (self._configuration.client_side_validation and
                max_speakers is not None and max_speakers < 2):  # noqa: E501
            raise ValueError("Invalid value for `max_speakers`, must be a value greater than or equal to `2`")  # noqa: E501

        self._max_speakers = max_speakers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranscribeDiarizationProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranscribeDiarizationProperties):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranscribeDiarizationProperties):
            return True

        return self.to_dict() != other.to_dict()
