# coding: utf-8

"""
    Speech Services API version 2024-11-15

    Speech Services API version 2024-11-15.  # noqa: E501

    OpenAPI spec version: 2024-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TranscriptionLocales(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transcribe': 'list[str]',
        'submit': 'list[str]'
    }

    attribute_map = {
        'transcribe': 'Transcribe',
        'submit': 'Submit'
    }

    def __init__(self, transcribe=None, submit=None, _configuration=None):  # noqa: E501
        """TranscriptionLocales - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._transcribe = None
        self._submit = None
        self.discriminator = None

        if transcribe is not None:
            self.transcribe = transcribe
        if submit is not None:
            self.submit = submit

    @property
    def transcribe(self):
        """Gets the transcribe of this TranscriptionLocales.  # noqa: E501


        :return: The transcribe of this TranscriptionLocales.  # noqa: E501
        :rtype: list[str]
        """
        return self._transcribe

    @transcribe.setter
    def transcribe(self, transcribe):
        """Sets the transcribe of this TranscriptionLocales.


        :param transcribe: The transcribe of this TranscriptionLocales.  # noqa: E501
        :type: list[str]
        """

        self._transcribe = transcribe

    @property
    def submit(self):
        """Gets the submit of this TranscriptionLocales.  # noqa: E501


        :return: The submit of this TranscriptionLocales.  # noqa: E501
        :rtype: list[str]
        """
        return self._submit

    @submit.setter
    def submit(self, submit):
        """Sets the submit of this TranscriptionLocales.


        :param submit: The submit of this TranscriptionLocales.  # noqa: E501
        :type: list[str]
        """

        self._submit = submit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranscriptionLocales, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranscriptionLocales):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranscriptionLocales):
            return True

        return self.to_dict() != other.to_dict()
